"""
email_digest.py — Delivery: CXO Weekly Email Digest
-----------------------------------------------------
Sends a proactive Monday morning promotional summary to CXO stakeholders
without them having to ask — the highest-value interface for senior leaders.

Cost: £15–20/mo via SendGrid Essentials (50K emails/month).
Build time: 1–2 days.

Setup:
  Set SENDGRID_API_KEY, EMAIL_FROM, EMAIL_TO in .env

Schedule with cron (every Monday 7:30 AM):
  30 7 * * 1 python delivery/email_digest.py

Or with Python scheduler:
  python delivery/email_digest.py --schedule
"""

import argparse
import json
import os
import schedule
import time
from datetime import datetime
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from dotenv import load_dotenv

from agents.orchestrator import run_pipeline

load_dotenv()

# Weekly digest queries — the four most important CXO questions
WEEKLY_DIGEST_QUERIES = [
    "What was the promotional uplift from the most recent campaign across all regions?",
    "Which region performed best in the latest campaign?",
    "Which SKUs drove the highest incremental volume this period?",
    "How did inventory movement compare during the promotional window vs the prior week?",
]


def build_digest_html(results: list[dict]) -> str:
    """Build the HTML email body from pipeline results."""
    date_str = datetime.now().strftime("%A %d %B %Y")
    sections = []
    for i, r in enumerate(results, 1):
        status_icon = "✅" if r["status"] == "success" else "⚠️"
        answer_html = r.get("formatted_answer", "No data available.").replace("\n", "<br>")
        sections.append(f"""
        <tr>
            <td style="padding: 16px; border-bottom: 1px solid #e5e7eb;">
                <p style="margin: 0 0 4px 0; font-size: 13px; color: #6b7280;">{status_icon} {r['query']}</p>
                <p style="margin: 0; font-size: 15px; color: #111827;">{answer_html}</p>
            </td>
        </tr>
        """)

    body = "\n".join(sections)
    return f"""
    <html>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f9fafb; margin: 0; padding: 24px;">
        <div style="max-width: 680px; margin: 0 auto; background: #fff; border-radius: 8px; border: 1px solid #e5e7eb;">
            <div style="padding: 24px 24px 0; border-bottom: 1px solid #e5e7eb;">
                <p style="margin: 0; font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em;">FMCG ANALYTICS · WEEKLY DIGEST</p>
                <h1 style="margin: 8px 0; font-size: 22px; color: #111827;">Promotional Performance Summary</h1>
                <p style="margin: 0 0 16px 0; font-size: 14px; color: #6b7280;">{date_str}</p>
            </div>
            <table style="width: 100%; border-collapse: collapse;">
                {body}
            </table>
            <div style="padding: 16px 24px; background: #f9fafb; border-top: 1px solid #e5e7eb; border-radius: 0 0 8px 8px;">
                <p style="margin: 0; font-size: 12px; color: #9ca3af;">
                    Generated by FMCG AI Analytics Assistant · Numbers validated by Python before delivery ·
                    <a href="mailto:{os.getenv('EMAIL_FROM', 'analytics@yourdomain.com')}?subject=Analytics query">Ask a follow-up question</a>
                </p>
            </div>
        </div>
    </body>
    </html>
    """


def send_digest() -> None:
    """Run all digest queries and send the email."""
    print(f"[{datetime.now().isoformat()}] Building weekly digest...")
    results = []
    for query in WEEKLY_DIGEST_QUERIES:
        print(f"  Running: {query[:60]}...")
        result = run_pipeline(query)
        results.append({
            "query": query,
            "status": result.status,
            "formatted_answer": result.formatted_answer,
        })

    html = build_digest_html(results)
    subject = f"FMCG Analytics: Weekly Digest — {datetime.now().strftime('%d %b %Y')}"

    sg = SendGridAPIClient(os.getenv("SENDGRID_API_KEY"))
    recipients = os.getenv("EMAIL_TO", "").split(",")
    for email in recipients:
        msg = Mail(
            from_email=os.getenv("EMAIL_FROM"),
            to_emails=email.strip(),
            subject=subject,
            html_content=html,
        )
        response = sg.send(msg)
        print(f"  Email sent to {email.strip()} — status {response.status_code}")

    print(f"[{datetime.now().isoformat()}] Digest sent to {len(recipients)} recipient(s).")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--schedule", action="store_true", help="Run on schedule (Monday 7:30 AM)")
    parser.add_argument("--now", action="store_true", help="Send digest immediately")
    args = parser.parse_args()

    if args.schedule:
        schedule.every().monday.at("07:30").do(send_digest)
        print("📅 Weekly digest scheduler running. Ctrl+C to stop.")
        while True:
            schedule.run_pending()
            time.sleep(60)
    else:
        # Default: send immediately (useful for testing)
        send_digest()
